env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react/recommended"
  - "plugin:sonarjs/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "react"
  - "sonarjs"
  - "import"
settings:
  react:
    version: detect
  import/resolver:
    typescript:
      project: .
rules:
  accessor-pairs: error
  array-callback-return:
    - error
    - allowImplicit: true
  arrow-body-style: error
  class-methods-use-this: error
  complexity:
    - error
    - 7
  curly:
    - error
    - multi
  default-case-last: error
  default-param-last: error
  dot-notation:
    - error
    - allowKeywords: true
  eqeqeq:
    - error
    - smart
  grouped-accessor-pairs: error
  guard-for-in: error
  import/no-internal-modules:
    - error
    - allow:
        - assets/*
  max-classes-per-file:
    - error
    - 1
  no-alert: error
  no-await-in-loop: error
  no-caller: error
  no-console:
    - warn
    - allow:
        - warn
        - error
  no-constructor-return: error
  no-div-regex: error
  no-else-return: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-extra-parens: "off"
  no-fallthrough: error
  no-floating-decimal: error
  no-implicit-coercion:
    - error
    - allow:
        - "!!"
  no-implicit-globals: error
  no-implied-eval: error
  no-invalid-this: error
  no-loop-func: error
  no-loss-of-precision: error
  no-promise-executor-return: error
  no-template-curly-in-string: error
  no-unreachable-loop: error
  no-unsafe-optional-chaining: error
  no-unused-expressions: error
  no-useless-backreference: error
  prefer-arrow-callback: error
  quotes:
    - error
    - double
    - avoidEscape: true
  react/display-name: off
  react/prop-types: off
  react/react-in-jsx-scope: off
  require-atomic-updates: error
