name: Api checks

on:
  push:
    paths:
      - .github/workflows/api-checks.yaml
      - "server/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn workspace server install
      - run: yarn workspace server run checks
