name: Client checks

on:
  push:
    paths:
      - .github/workflows/client-check.yaml
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn workspace client install
      - run: yarn workspace client run checks
