name: Heroku deploy

on:
  push:
    paths:
      - server/**
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "vroommates-agerard57"
          heroku_email: "agerard57@protonmail.com"
          appdir: "server"