name: Markdown

on:
  push:
    paths:
      - .github/workflows/markdown.yaml
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npx markdownlint-cli .
